#[derive(Debug, Clone)]
pub enum LojbanAST {
    Text(Vec<LojbanAST>),
    Paragraph(Vec<LojbanAST>),
    Statement(Vec<LojbanAST>),
    Sentence(Vec<LojbanAST>),
    Sumti(Vec<LojbanAST>),
    Selbri(Vec<LojbanAST>),
    Brivla(Vec<LojbanAST>),
    Gismu(Vec<LojbanAST>),
    Lujvo(Vec<LojbanAST>),
    Fuhivla(Vec<LojbanAST>),
    Negation(Vec<LojbanAST>),
    Tag(Vec<LojbanAST>),
    Quoting(Vec<LojbanAST>),
    Abstractor(Vec<LojbanAST>),
    Cmavo(String, Vec<LojbanAST>), // kind and content
    FreeModifier(Vec<LojbanAST>),
    Syllable(Vec<LojbanAST>),
    ConsonantCluster(Vec<LojbanAST>),
    Token(String),
    Cmene(String),
    Prenex(Vec<LojbanAST>),
    Bridi(Vec<LojbanAST>),
}
